default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: AcademyRootPassword
  host: localhost
  pool: 5

development:
  <<: *default
  database: blog_app_development

test:
  <<: *default
  database: blog_app_test

production:
  <<: *default
  database: blog_app_production
  username: blog_app
  password: <%= ENV["Ruby_DB@17/2025"] %>
